// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as FamilyApi from "../../../index.js";

export declare namespace PetsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PetsClient {
    protected readonly _options: NormalizedClientOptions<PetsClient.Options>;

    constructor(options: PetsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FamilyApi.ListPetsRequest} request
     * @param {PetsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.FamilyApiError}
     * @throws {@link errors.FamilyApiTimeoutError}
     *
     * @example
     *     await client.pets.listPets()
     */
    public listPets(
        request: FamilyApi.ListPetsRequest = {},
        requestOptions?: PetsClient.RequestOptions,
    ): core.HttpResponsePromise<FamilyApi.Pet[]> {
        return core.HttpResponsePromise.fromPromise(this.__listPets(request, requestOptions));
    }

    private async __listPets(
        request: FamilyApi.ListPetsRequest = {},
        requestOptions?: PetsClient.RequestOptions,
    ): Promise<core.WithRawResponse<FamilyApi.Pet[]>> {
        const { limit } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "pets",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as FamilyApi.Pet[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FamilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/pets");
    }

    /**
     * @param {FamilyApi.CreatePetRequest} request
     * @param {PetsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.FamilyApiError}
     * @throws {@link errors.FamilyApiTimeoutError}
     *
     * @example
     *     await client.pets.createPet({
     *         name: "name"
     *     })
     */
    public createPet(
        request: FamilyApi.CreatePetRequest,
        requestOptions?: PetsClient.RequestOptions,
    ): core.HttpResponsePromise<FamilyApi.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__createPet(request, requestOptions));
    }

    private async __createPet(
        request: FamilyApi.CreatePetRequest,
        requestOptions?: PetsClient.RequestOptions,
    ): Promise<core.WithRawResponse<FamilyApi.Pet>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "pets",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as FamilyApi.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FamilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/pets");
    }

    /**
     * @param {FamilyApi.GetPetRequest} request
     * @param {PetsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.FamilyApiError}
     * @throws {@link errors.FamilyApiTimeoutError}
     *
     * @example
     *     await client.pets.getPet({
     *         petId: "petId"
     *     })
     */
    public getPet(
        request: FamilyApi.GetPetRequest,
        requestOptions?: PetsClient.RequestOptions,
    ): core.HttpResponsePromise<FamilyApi.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__getPet(request, requestOptions));
    }

    private async __getPet(
        request: FamilyApi.GetPetRequest,
        requestOptions?: PetsClient.RequestOptions,
    ): Promise<core.WithRawResponse<FamilyApi.Pet>> {
        const { petId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `pets/${core.url.encodePathParam(petId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as FamilyApi.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FamilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/pets/{petId}");
    }
}
